Update Syntax and spellings.
spring-projects/spring-ws pull request #1161
Opened 2020-10-01 17:08 UTC by DarkMatter188

2020-10-01 17:08 UTC, pivotal-issuemaster commented
@DarkMatter188 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ws&pullRequestId=1161)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-ws&pullRequestId=1161) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-11-23 16:51 UTC, gregturn requested changes

2020-11-23 16:51 UTC, gregturn commented on README.adoc
>  * Experiment against a new image before submitting your pull request.
I'd simply drop the extra "a".

2020-11-23 16:51 UTC, gregturn commented on README.adoc
"All of these use cases are great reasons to run what Jenkins does on your local machine."

2022-11-16 17:52 UTC, pivotal-cla commented
@DarkMatter188 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ws&pullRequestId=1161)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-ws&pullRequestId=1161) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-11-16 17:53 UTC, gregturn commented
Thanks @DarkMatter188. I've taken your patch, polished it, and merged to to `4.0.x`.

2022-11-16 17:53 UTC, closed without merging

2022-11-16 21:09 UTC, gregturn commented
Backported to `main`